# Generated by Django 3.0.7 on 2020-06-26 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiostation',
            name='streaming_link',
            field=models.URLField(blank=True, max_length=300, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
