# Generated by Django 3.0.7 on 2020-06-26 12:05

from django.db import migrations, models
import recordings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_auto_20200626_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiostation',
            name='streaming_link',
            field=models.URLField(blank=True, max_length=300, null=True, validators=[recordings.validators.validate_streaming_url]),
        ),
    ]
