# Generated by Django 3.0.7 on 2020-06-26 16:58

from django.db import migrations, models
import recordings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0006_recording_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='file',
            field=models.FileField(blank=True, upload_to='media/', validators=[recordings.validators.is_mp3_file]),
        ),
    ]
