# Generated by Django 3.0.7 on 2020-06-26 17:07

from django.db import migrations, models
import recordings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0007_auto_20200626_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[recordings.validators.is_mp3_file]),
        ),
    ]
