# Generated by Django 3.0.7 on 2020-07-07 13:26

from django.db import migrations, models
import recordings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0009_recording_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='recordings', validators=[recordings.validators.is_mp3_file]),
        ),
    ]
