# Generated by Django 3.0.7 on 2020-07-20 14:56

from django.db import migrations, models
import recordings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0011_auto_20200707_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[recordings.validators.is_mp3_file]),
        ),
    ]
