# Generated by Django 3.0.7 on 2020-07-27 16:44

from django.db import migrations, models
import recordings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0013_auto_20200723_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[recordings.validators.validate_over_one_character]),
        ),
        migrations.AlterField(
            model_name='recording',
            name='title',
            field=models.CharField(max_length=50, null=True, validators=[recordings.validators.validate_over_one_character]),
        ),
    ]
