# Generated by Django 3.0.7 on 2020-07-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0014_auto_20200727_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('in progress', 'in progress'), ('complete', 'complete'), ('failed', 'failed')], default='pending', max_length=15),
        ),
    ]
